# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('class_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('class_home', models.CharField(max_length=30)),
                ('class_createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 't_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClassTeacher',
            fields=[
                ('class_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_class_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TGroup',
            fields=[
                ('group_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('group_leader', models.CharField(blank=True, max_length=30, null=True)),
                ('group_it_leader', models.CharField(blank=True, max_length=30, null=True)),
                ('group_createtime', models.DateTimeField()),
                ('class_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TJob',
            fields=[
                ('job_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=30)),
                ('job_info', models.CharField(max_length=255)),
                ('job_createtime', models.DateTimeField()),
                ('class_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStudent',
            fields=[
                ('student_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('student_pwd', models.CharField(max_length=30)),
                ('class_id', models.CharField(max_length=30)),
                ('group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('student_createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 't_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSubject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('teacher_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_teacher',
                'managed': False,
            },
        ),
    ]
